### ISSUE TITLE
Modify links for GitHub Pages

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-documents#12]
## Overview
Modify links in all documents for GitHub Pages.

## Details
To see the documents in the Github Pages, all links should be modified to refer to the Github Pages.

## Conditions for close
All links are modified.

## Supplement
NA

**Comment by daredevil3435** [comment]
Hey, can you assign me this project but i am totally new in this contribution field, can you guide me?

**Comment by 200km** [comment]
Thank you for your comment. Please create a pull request after you read the issue and the [README of the related repository](https://github.com/ut-issl/s2e-core).

**Comment by daredevil3435** [comment]
As I am new contributor could you please simplify problem statement for me? @200km

**Comment by 200km** [comment]
It was just a small mistake, and we don't need fix all links.  
This issue can be closed after the PR #22 is merged.
