### ISSUE TITLE
Can not build S2E on Ubuntu Docker

### ISSUE THREAD

**Issue by isp-t-shimizu** [ut-issl/s2e-documents#19]
## Overview
- Can not build S2E on Ubuntu Docker.  It seems Docker for Ubuntu doesn't run properly.

### Description
- I couldn't build in Section 3.5 in the [HowToCompileWithUbuntuInDocker.md](https://github.com/ut-issl/s2e-documents/blob/main/General/HowToCompileWithUbuntuInDocker.md), because of couldn't find `s2e-core` directory in `work` directory.
- In stead of `s2e-core`, I found an empty directory, `s2e_core_oss` in the `work` directory in docker container.

### Conditions of occurrence
- The environment in which the bug occurs, the condition, parameters, etc.
    - Ubuntu 18.04
    - s2e-documents : main branch [c091abd](https://github.com/ut-issl/s2e-documents/commit/c091abd3e640dd03811f36a3af625b2252166b67)
    - s2e-core : develop branch [95c9b7c](https://github.com/ut-issl/s2e-core/commit/95c9b7c33aa6de0f18602e6d262008d4343e8275)

- I confirmed it is reproducible.
 
### Problem 
- The document, [HowToCompileWithUbuntuInDocker.md](https://github.com/ut-issl/s2e-documents/blob/main/General/HowToCompileWithUbuntuInDocker.md) expects to use `s2e-core` directory in section 3.1, but the script to make a docker container uses `s2e_core_oss` instead of `s2e-core`.  It should be `s2e-core`.
It is in the `run_core` function in [setup_docker.sh](https://github.com/ut-issl/s2e-core/blob/develop/scripts/Docker_Ubuntu/setup_docker.sh) in s2e-core.

###  Additional information
- [HowToCompileWithUbuntuInDocker.md](https://github.com/ut-issl/s2e-documents/blob/main/General/HowToCompileWithUbuntuInDocker.md)
- [setup_docker.sh](https://github.com/ut-issl/s2e-core/blob/develop/scripts/Docker_Ubuntu/setup_docker.sh)

## Task
- [ ] Fix [setup_docker.sh](https://github.com/ut-issl/s2e-core/blob/develop/scripts/Docker_Ubuntu/setup_docker.sh)

```diff
 function run_core {
-    docker run -it -d --cap-add=SYS_PTRACE --security-opt="seccomp=unconfined" -v /$(realpath ../../../s2e_core_oss):/home/s2e/work/s2e_core_oss --name issl-1 -p 2222:22 issl:latest
+    docker run -it -d --cap-add=SYS_PTRACE --security-opt="seccomp=unconfined" -v /$(realpath ../../../s2e-core):/home/s2e/work/s2e-core --name issl-1 -p 2222:22 issl:latest
 }

```

## Scope of influence
- When you use S2E on Ubuntu Docker environment, you can't build S2E in the Docker.

## Supplement
- I confirmed it works well to use above revision of "diff" in "Task"

**Comment by 200km** [comment]
@isp-t-shimizu Thank you Shimizu-san to find the issue. The old description is remained before the movement from Gitlab. Could you make a Pull Request for the modification to 's2e-core'?

**Comment by isp-t-shimizu** [comment]
@200km Sure. Will send a pull request soon later.  Additionally, I'm facing another minor issues. Let me check and will fix them, too.

**Comment by 200km** [comment]
Thanks!
