### ISSUE TITLE
Revise some parts of the tutorial

### ISSUE THREAD

**Issue by kai0722** [ut-issl/s2e-documents#45]
## Overview
Revise some parts of the tutorial

## Details
Some parts of the tutorial need to be revised especially for beginners

## Conditions for close
When revisions are complete

## Supplement
I made an explanation file below to suggest a revision
[tutorial_struggling.txt](https://github.com/ut-issl/s2e-documents/files/10154004/tutorial_struggling.txt)

## Note
NA

**Comment by 200km** [comment]
@kai0722 Thank you very much for your suggestion to improve the tutorial documents!

**Comment by 200km** [comment]
I assigned you for this issue.  
The suggestion for the tutorial 8 and 9, I agree with you. so please make a pull request.  
For the tutorial 10 to 12 I will fix the description of the tutorial.
